apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: default 
  name: mysql
spec:
  serviceName: "mysql"
  podManagementPolicy: Parallel
  replicas: 1
  template:
    metadata:
      labels:
        component: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: gmt.reg.me/test/mysql:5.7 
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 3306 
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: mysql-claim
              mountPath: /var/lib/mysql
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: mysql-claim
          persistentVolumeClaim:
            claimName: mysql-pv-0
